apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster1
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels: 
      name: "cluster1"
  clusterReplicas: 1
