apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedPersistentVolumeClaim
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  template:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  placement:
    clusterNames:
    - east1
    - east2
    - west2
