apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedIngress
metadata:
  name: pacman
spec:
  template:
    spec:
      rules:
      - host: pacman.example1.com
        http:
          paths:
          - path: /
            backend:
              serviceName: pacman
              servicePort: 80
  placement:
    clusterNames:
    - east1
    - east2
    - west2
