---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedClusterRole
metadata:
  name: pacman
spec:
  placement:
    clusterNames:
    - east1
    - east2
    - west2
  template:
    metadata: {}
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      - nodes
      verbs:
      - get
      - watch
      - list
