---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedClusterRoleBinding
metadata:
  name: pacman
spec:
  placement:
    clusterNames:
    - east1
    - east2
    - west2
  template:
    metadata: {}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: pacman
    subjects:
    - kind: ServiceAccount
      name: pacman
      namespace: pacmanv3

