---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedServiceAccount
metadata:
  name: pacman
spec:
  placement:
    clusters:
    - name: feddemocl1
    - name: feddemocl2
    - name: feddemocl3
  template:
    metadata:
      labels:
        name: pacman
