---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedClusterRole
metadata:
  name: pacman
spec:
  placement:
    clusters:
    - name: feddemocl1
    - name: feddemocl2
    - name: feddemocl3
  template:
    metadata:
      labels:
        name: pacman
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      - nodes
      verbs:
      - get
      - watch
      - list
